class CreateFeedbacks < ActiveRecord::Migration[7.2]
  def change
    create_table :feedbacks do |t|
      t.references :account, null: false, foreign_key: true
      t.references :source, null: false, foreign_key: true
      t.string :external_id                           # ID in origin system, for deduplication
      t.text :content, null: false                    # the actual feedback text
      t.string :author_email
      t.string :author_name
      t.integer :sentiment                            # enum: positive=0, neutral=1, negative=2
      t.string :topics, array: true, default: []      # tags generated by gpt-4.1-mini
      t.jsonb :metadata, default: {}                  # extra data from source (rating, url, etc.)
      t.datetime :received_at                         # when it happened in origin
      t.datetime :processed_at                        # when embedding + classification was done
      t.timestamps
    end

    # Unique constraint: one feedback per external_id per source
    add_index :feedbacks, [:source_id, :external_id], unique: true, where: "external_id IS NOT NULL"
    add_index :feedbacks, [:account_id, :received_at]
    add_index :feedbacks, :sentiment
    add_index :feedbacks, :topics, using: :gin
    add_index :feedbacks, :processed_at, where: "processed_at IS NULL", name: "index_feedbacks_unprocessed"
  end
end
